version : "3.7"
services:
  thyme:
    image: e7217/autobuild_thyme
    container_name: thyme
    ports:
      - "17577:7577"
      - "17578:7578"
      - "17582:7582"
      - "18883:8883"
      - "11883:1883"
    restart:
      always
    stdin_open:
      true
    tty:
      true

  mobius:
    image: e7217/mobius_autobuild
    container_name: mobius
    ports:
      - "7577:7577"
      - "7578:7578"
      - "7582:7582"
      - "8883:8883"
      - "1883:1883"
    restart:
      always
    stdin_open:
      true
    tty:
      true

  mobiusdb:
    image: mysql:5.7
    container_name: mobiusdb
    command:
#      --default-authentication-plugin=mysql_native_password
      --innodb-use-native-aio=0
#      --disable-partition-engine-check
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
    restart:
      always

  adminer:
    image:
      adminer
    restart:
      always
    ports:
      - "8080:8080"

  mqtt-broker:
    image:
      eclipse-mosquitto
    container_name:
      mqtt-broker
    restart:
      always
    volumes:
      - ./mqtt/:/mosquitto/
    ports:
      - "1883:1883"
      - "9001:9001"
